name: Tag Latest Green Commit

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Run Pytest
      run: pytest
    - name: Tag if Pytest Passed
      run: git tag latest
