name: Tag Latest Green Commit

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

    - uses: actions/checkout@v3

    - name: Setup Python
      uses: actions/setup-python@v4

    - name: Install Python Packages
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run Pytest
      run: pytest

    - name: Build docker
      run: docker build .

    - name: Tag if all green
      run: |
        git tag latest -f
        git push origin latest --force
